// Curated Phosphor icon set dùng cho khu Staff/Admin — import 1 chỗ để nhất quán.
// Thay thế toàn bộ emoji (taste-skill: ANTI-EMOJI). Weight/size set tại chỗ dùng.
export {
  House,
  ListChecks,
  ChartLineUp,
  ChatCircleDots,
  Bell,
  Briefcase,
  Wrench,
  Package,
  Timer,
  WarningCircle,
  WarningOctagon,
  CheckCircle,
  X,
  Gear,
  Clock,
  Star,
  Power,
  Pause,
  PlayCircle,
  ArrowRight,
  ArrowLeft,
  CaretRight,
  MagnifyingGlass,
  Megaphone,
  ClipboardText,
  UserCircle,
  UsersThree,
  SignOut,
  Translate,
  PaperPlaneTilt,
  Tray,
  Storefront,
  Tag,
  CalendarBlank,
  Circle,
  CheckSquare,
  Prohibit,
  Hourglass,
  Plus,
  UserPlus,
  ShieldCheck,
  DotsThreeVertical,
  PencilSimple,
  Phone,
} from "@phosphor-icons/react";
