// <auto-generated />
using System;
using LG.Core.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LG.Core.Infrastructure.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20260515021843_RenameZaloToEmailNotification")]
    partial class RenameZaloToEmailNotification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LG.Core.Domain.Finance.BalanceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsReconciled")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ReconciledBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SnapshotAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<int>("TotalActiveWallets")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAvailableVnd")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("TotalBalanceVnd")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("TotalFrozenVnd")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("TotalWalletsWithBalance")
                        .HasColumnType("integer");

                    b.Property<decimal?>("VarianceFromPrev")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.ToTable("BalanceSnapshot", "finance");
                });

            modelBuilder.Entity("LG.Core.Domain.Finance.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountHolder")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Branch")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WebhookService")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BankAccount", "finance");
                });

            modelBuilder.Entity("LG.Core.Domain.Finance.BankWebhookLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AmountVnd")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("BankAccountId")
                        .HasColumnType("integer");

                    b.Property<string>("BankRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("MatchedTopupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProcessingStatus")
                        .HasColumnType("integer");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransferContent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BankWebhookLog", "finance");
                });

            modelBuilder.Entity("LG.Core.Domain.Finance.CreditLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentDebtVnd")
                        .HasColumnType("decimal(18,0)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<short>("DueDateDays")
                        .HasColumnType("smallint");

                    b.Property<DateOnly?>("ExpiresAt")
                        .HasColumnType("date");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GrantedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaxCreditVnd")
                        .HasColumnType("decimal(18,0)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CreditLimit", "finance");
                });

            modelBuilder.Entity("LG.Core.Domain.Finance.CustomerAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DistrictCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProvinceCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("WardCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("CustomerAddress", "finance");
                });

            modelBuilder.Entity("LG.Core.Domain.Finance.CustomerKYC", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateOfBirthOnId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullNameOnId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("IdBackUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IdFrontUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IdNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("KycExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KycLevel")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlaceOfOrigin")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PlaceOfResidence")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("SelfieUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("VideoVerificationUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("CustomerKYC", "finance");
                });

            modelBuilder.Entity("LG.Core.Domain.Finance.CustomerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<decimal>("LifetimeValueVnd")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PreferredChannel")
                        .HasColumnType("integer");

                    b.Property<string>("ReferralCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ReferredById")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VipTierId")
                        .HasColumnType("uuid");

                    b.Property<string>("ZaloUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("CustomerProfile", "finance");
                });

            modelBuilder.Entity("LG.Core.Domain.Finance.DailyRevenueReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ExchangeProfitLossVnd")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ExchangeRateAvg")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("InspectionFeeRevenueVnd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InsuranceFeeRevenueVnd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PenaltyRevenueVnd")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ServiceFeeRevenueVnd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ShipFeeRevenueVnd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalCnyPurchased")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalOrdersCompleted")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalRevenueVnd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalVndCollected")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("DailyRevenueReport", "finance");
                });

            modelBuilder.Entity("LG.Core.Domain.Finance.DebtRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreditLimitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DebtAmountVnd")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsOverdue")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LinkedOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("OverdueSince")
                        .HasColumnType("date");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("ReminderSentCount")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("DebtRecord", "finance");
                });

            modelBuilder.Entity("LG.Core.Domain.Finance.EmailNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("MessageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemplateData")
                        .HasColumnType("text");

                    b.Property<int?>("TemplateType")
                        .HasColumnType("integer");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("EmailNotification", "finance");
                });

            modelBuilder.Entity("LG.Core.Domain.Finance.FeeRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<decimal>("InspectionFeePct")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("InspectionMaxVnd")
                        .HasColumnType("decimal(10,0)");

                    b.Property<decimal>("InspectionMinVnd")
                        .HasColumnType("decimal(10,0)");

                    b.Property<decimal>("InsuranceBasicPct")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("InsuranceFullPct")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("IntlShipPerKgVnd")
                        .HasColumnType("decimal(10,0)");

                    b.Property<short>("IntlShipVolDivisor")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MinChargeKg")
                        .HasColumnType("decimal(5,3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("PlatformId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ServiceFeePct")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("StorageDailyPerKgVnd")
                        .HasColumnType("decimal(10,0)");

                    b.Property<Guid?>("VipTierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("FeeRule", "finance");
                });

            modelBuilder.Entity("LG.Core.Domain.Finance.FraudDetection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("EvidenceJson")
                        .HasColumnType("text");

                    b.Property<int?>("FraudType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RiskScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("FraudDetection", "finance");
                });

            modelBuilder.Entity("LG.Core.Domain.Finance.PaymentLock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LockType")
                        .HasColumnType("integer");

                    b.Property<decimal>("LockedAmountVnd")
                        .HasColumnType("decimal(18,0)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ReleaseReason")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PaymentLock", "finance");
                });

            modelBuilder.Entity("LG.Core.Domain.Finance.PlatformReconcile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlipayStatementUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("CnySpent")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("PlatformAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ReconcileDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ReconciledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReconciledBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ServiceFeeCollectedVnd")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("VarianceVnd")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("VndEquivalent")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.ToTable("PlatformReconcile", "finance");
                });

            modelBuilder.Entity("LG.Core.Domain.Finance.RefundProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GrossAmountVnd")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("NetRefundVnd")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("PenaltyPct")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("PenaltyVnd")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int?>("Reason")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TriggeredBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WalletTransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RefundProcess", "finance");
                });

            modelBuilder.Entity("LG.Core.Domain.Finance.TopupRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountVnd")
                        .HasColumnType("decimal(18,0)");

                    b.Property<bool>("AutoMatched")
                        .HasColumnType("boolean");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MatchedBankRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QrUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransferContent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WalletTransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TopupRequest", "finance");
                });

            modelBuilder.Entity("LG.Core.Domain.Finance.TransactionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Direction")
                        .HasColumnType("integer");

                    b.Property<bool>("IsReversible")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("TransactionType", "finance");
                });

            modelBuilder.Entity("LG.Core.Domain.Finance.VipTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CashbackPct")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DepositPctOverride")
                        .HasColumnType("decimal(5,4)");

                    b.Property<bool>("FreeInspection")
                        .HasColumnType("boolean");

                    b.Property<short>("FreeStorageDays")
                        .HasColumnType("smallint");

                    b.Property<short>("Level")
                        .HasColumnType("smallint");

                    b.Property<decimal>("MinSpendVnd")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("PrioritySupport")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ServiceFeeDiscountPct")
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("Id");

                    b.ToTable("VipTier", "finance");
                });

            modelBuilder.Entity("LG.Core.Domain.Finance.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvailableBalance")
                        .HasColumnType("decimal(18,0)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("FrozenBalance")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("FrozenReason")
                        .HasColumnType("text");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PendingRefundVnd")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("TotalDepositedEver")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("TotalSpentEver")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.ToTable("Wallet", "finance");
                });

            modelBuilder.Entity("LG.Core.Domain.Finance.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("BalanceBefore")
                        .HasColumnType("decimal(18,0)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("WalletTransaction", "finance");
                });

            modelBuilder.Entity("LG.Core.Domain.Finance.WithdrawRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountHolder")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("AmountVnd")
                        .HasColumnType("decimal(18,0)");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("BankAccountNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("FeeVnd")
                        .HasColumnType("decimal(18,0)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("NetAmountVnd")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransferRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WalletTransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("WithdrawRequest", "finance");
                });
#pragma warning restore 612, 618
        }
    }
}
